name: Rust Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Pre-requisites
      run: sudo apt install libdbus-1-dev pkg-config libtss2-sys1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
