name: Rust Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true
    - name: Pre-requisites
      run: sudo apt install libdbus-1-dev pkg-config libtss2-sys1 libpcsclite-dev
    - name: Create empty config file
      run: mkdir -p ~/.config/io.linux-tks/ && touch ~/.config/io.linux-tks/service.toml
    - name: Build
      uses: actions-rs/cargo@v1
      with:
          command: build
          args: --verbose
    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
          command: test
          args: --verbose
